### ISSUE TITLE
[Multiple controllers] Using ros_control in robot IMAU

### ISSUE THREAD

**Issue by dario-pedro** [ros-controls/ros_control#245]
Hi everyone,

My robot (IMAU) has 3 controllers:

```
 - imau_elevator_controller
 - imau_right_gripper_controller
 - imau_left_gripper_controller
```

Each controller contains the joints information, something like:

```
imau_elevator_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
     - elevator_base_joint
     - elevator_joint
     - prismatic_1_joint
     - prismatic_2_joint
     - gripper_pan_joint
  gains:
    elevator_base_joint: {p: 10000.0, i: 700.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
    elevator_joint: {p: 100000.0, i: 700.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
    prismatic_1_joint: {p: 1000.0, i: 70.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
    prismatic_2_joint: {p: 1000.0, i: 70.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
    gripper_pan_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
  constraints:
      goal_time: 5555.6
      stopped_velocity_tolerance: 5555.5
      elevator_base_joint: {trajectory: 5555.1, goal: 5555.1}
      elevator_joint: {trajectory: 5555.1, goal: 5555.1}
      prismatic_1_joint: {trajectory: 5555.1, goal: 5555.1}
      prismatic_2_joint: {trajectory: 5555.1, goal: 5555.1}
      gripper_pan_joint: {trajectory: 5555.1, goal: 5555.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
```

I've managed to load the controllers correctly and everything looks fine on rqt. But when I Start the controllers on rqt, only the last one that was loaded ( imau_left_gripper_controller) seems to be working. By working I mean that the joint_command change when I move the sliders on rqt.

The code can be found  [here](https://github.com/dario-pedro/imau), it was based on [baxter control](https://github.com/davetcoleman/baxter_cpp) by @davetcoleman .

Thanks in advance.

**Comment by bmagyar** [comment]
Could you please specify what you mean by "seems to be working"?

If it's rqt, screenshots could work but maybe more direct is if you'd call
Rosservice call /controller_manager/list_controllers

When you think it should all be up and running?
What is your full startup sequence?

**Comment by facmarques** [comment]
Hi,

I'm working with Dário and maybe I can explain further.
Ẃe wanted to have 3 (objective is to be generic as possible ) controllers launched from one node.
So we based ourselves on the Baxter Code by @davetcoleman, as baxter has also two arms.

Our sequence is as follows:

Launch robot description;
Controllers spawner;
Node;

The only controller that responds and generates commands it the last one to run inside our code.
If we have one controller that one responds, if we have two the second and so on. 
As you can see in the screenshots below. Only the left gripper has values in the command message (our output for the motors).

Thanks

It seems odd has we stepped into 
![controller_1](https://cloud.githubusercontent.com/assets/20779718/17306127/3413364e-5826-11e6-9260-05f45aa2f830.png)
![controller2](https://cloud.githubusercontent.com/assets/20779718/17306128/3578902e-5826-11e6-8114-d2819174f6a5.png)

**Comment by miguelprada** [comment]
Since all controllers seem to be running, could you check (e.g. by using `rostopic echo`) that the rqt plugin is really publishing the commands on every `/controller_manager/CONTROLLER_NAME/command` topic (should only publish for the currently selected controller in the widget, I think)?

Also, since you seem to be using the position interface-based joint trajectory controller, no PIDs are used and therefore the gain parameters don't need to be set.

**Comment by facmarques** [comment]
Hi,

Yes, we've checked that already (you are correct it only publishes one at a time). But only the  last controller that gets loaded responds.
We were testing several hypotheses for controlling, but thanks we will check the config files to remove te gains.

**Comment by miguelprada** [comment]
There should be no reason the controller manager only updates the last controller loaded, just tested this myself with two joint trajectory controllers acting on different joints of the same robot and both respond just fine.

Is the source code for your `RobotHW` implementation available somewhere? It is possible that the issue is lying there somewhere.

**Comment by bmagyar** [comment]
The rqt_joint_trajectory plugin only publishes to the currently active controller, and only on change I believe. If you don't touch it, no commands will be send. 

I'd recommend looking at the controller state outputs. Just simply 
`rostopic echo /imau_elevator_controller/state`
The error field here may give you hints as to what reference the controller is trying to track.

@miguelprada , this should be the part where those commands could get stuck IMHO, but it doesn't seem to be the case:
https://github.com/dario-pedro/imau/blob/master/src/Arm_interface.cpp#L93

**Comment by dario-pedro** [comment]
Hello,

@bmagyar  I've done`rostopic echo /imau_elevator_controller/state` , and when I move the sliders on rqt plugin nothing changes. The result is showed in the screenshot below:
![rostopic echo /imau_elevator_controller/state result](https://cloud.githubusercontent.com/assets/20140584/17325837/bcb2cc2e-58a5-11e6-9bd0-3fcda3d81b29.png)

@miguelprada , the `RobotHW` code can be found [here](https://github.com/dario-pedro/imau/blob/master/src/Arm_interface.cpp) , if u need any more information , please let me know.

**Comment by bmagyar** [comment]
Ok, this gives a starting point. 
When you send a new command via the rqt gui, a new goal should appear on the appropriate topic.
Since the joint traj controller directly subscribes to this topic, the new goal values should appear in the values of the `reflected` vector.
Are you sure, your controller is receiving the commands? All I can think of now is that the topic has been remapped.

**Comment by dario-pedro** [comment]
Hello,
We've tried to sort out the problem using rqt_graph, but we don't understand exactly what's happening. 

The prints below represent the result when you use the sliders of the different controllers.

![eleveator_controller on](https://cloud.githubusercontent.com/assets/20140584/17434359/e346307a-5b01-11e6-8a54-871f801de2dd.png)
![right_controller on](https://cloud.githubusercontent.com/assets/20140584/17434358/e345af1a-5b01-11e6-8509-3ba1953fb657.png)
![left_controller on](https://cloud.githubusercontent.com/assets/20140584/17434425/42a975cc-5b02-11e6-969b-c80cfbefc0cc.png)

We're going to try to investigate further into the ros_control code and try to understand what's happening.

**Comment by bmagyar** [comment]
Ok, so it seems there's no subscription to those topics. Just to double-check this, please untick "group actions" and "hide leaf topics" "hide dead sinks".

Please also run "rosservice call /controller_manager/list_controllers" and paste the output here.

**Comment by dario-pedro** [comment]
Hi again, 

> Ok, so it seems there's no subscription to those topics. Just to double-check this 

The only topic we subscribed is the actuator/motor_nanotec/joint_states on `arm_interface_sub = n.subscribe("/", 1000,&Arm_interface::handleAMotorResponse, this);` to get the robot current states on the `Arm_interface` . The topics we're publish are /actuator/motor_nanotech/"+controller_name+"/joint_command , 1 per controller , done in `joints_pub = nh.advertise<sensor_msgs::JointState>(/*/imau*/"/actuator/motor_nanotech/"+controller_name+"/joint_command", 1000);` .

The prints you requested are posted bellow: ( one for the right_arm and another for the left_arm )

![screenshot from 2016-08-09 10 08 14](https://cloud.githubusercontent.com/assets/20140584/17511300/380b62ae-5e1a-11e6-971c-f884e2a718b9.png)
![screenshot from 2016-08-09 10 09 05](https://cloud.githubusercontent.com/assets/20140584/17511301/380c934a-5e1a-11e6-9595-006dd9333ed4.png)

The screenshots looks similar , but only the imau_left_gripper_controller seems to be outputting commands.

The information from "rosservice call /controller_manager/list_controllers" is:

```
controller: 
  - 
    name: joint_state_controller
    state: running
    type: joint_state_controller/JointStateController
    hardware_interface: hardware_interface::JointStateInterface
    resources: []
  - 
    name: imau_elevator_controller
    state: running
    type: position_controllers/JointTrajectoryController
    hardware_interface: hardware_interface::PositionJointInterface
    resources: ['elevator_base_joint', 'elevator_joint', 'gripper_pan_joint', 'prismatic_1_joint', 'prismatic_2_joint']
  - 
    name: imau_right_gripper_controller
    state: running
    type: position_controllers/JointTrajectoryController
    hardware_interface: hardware_interface::PositionJointInterface
    resources: ['gripper_right_joint', 'gripper_support_right_joint']
  - 
    name: imau_left_gripper_controller
    state: running
    type: position_controllers/JointTrajectoryController
    hardware_interface: hardware_interface::PositionJointInterface
    resources: ['gripper_left_joint', 'gripper_support_left_joint']

```
