### ISSUE TITLE
Control multiple joints at the same time

### ISSUE THREAD

**Issue by ghost** [ros-controls/ros_control#366]
For example, there is a robot model with two controllers, here is the yaml file of the controls:
```
myrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  controller_1:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 10.0, i: 1.0, d: 0.01}

  #Velocity Controlle
  controller_2:
    type: effort_controllers/JointVelocityController
    joint: joint_2
    pid: {p: 100.0, i: 10.0, d: 0.01}
```
 Is there any way to control both controllers at the same time? It is best to use the gui tool. Any opinion will be appreciated.
