### ISSUE TITLE
[proposal] Add Multi Joint Controllers

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_control#85]
I'm running into a wall trying to create a controller that needs to control multiple joints/actuators. I believe a similar solution has been proposed here [Support multiple hardware interfaces in controllers](https://github.com/ros-controls/ros_control/issues/75) and a less similar idea of [composite controllers](https://github.com/ros-controls/ros_controllers/issues/12) but it seems to me a simpler solution would be to create controllers that operate on multiple joints/multiple sub-controllers.

This notion is something I've seen implemented effectively in the [dynamixel_hardware_interface](https://github.com/davetcoleman/clam/blob/master/dynamixel_hardware_interface/src/controller_manager.cpp#L554) originally created by @arebgun. In this implementation you can load **MultiJointController**s basically the same was as you load **SingleJointController**s except you also pass it in it's `init()` function a list of pointers to sub controllers that it can use to actually control hardware. You continue to have your normal `controllers.yaml` file but you now have an additional configuration file similar to:

```
clam_trajectory_controller:
    type: dynamixel_hardware_interface/JointTrajectoryActionController
    dependencies:
        - shoulder_pan_controller
        - gripper_roll_controller
        - shoulder_pitch_controller
        ...
    joint_trajectory_action_node:
        min_velocity: 0.0
        constraints:
            goal_time: 0.3
            shoulder_pan_joint:
                goal: 0.2
            gripper_roll_joint:
                goal: 0.2
            shoulder_pitch_joint:
                goal: 0.2
            ...
```

This allows you to easily implement a joint trajectory action controller or a controller that listens to ROS messages that contain commands for multiple joints (as is the case with Baxter).

Your launch file for the joint trajectory action controller might then look like:

```
  <rosparam file="$(find clam_controller)/config/clam_trajectory_controller.yaml" command="load"/>
  <node name="arm_trajectory_controller_spawner" pkg="dynamixel_hardware_interface" type="controller_spawner.py"
        args="--manager=clam_controller_manager
              clam_trajectory_controller"
        output="screen"/>
```

What are you guy's thoughts on supporting this?
